[package]
name = "cert-rs-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
# -- App Libs
# -- Web
axum = { workspace = true }
# lib-auth = { path = "../../libs/lib-auth" }
lib-core = { path = "../../libs/lib-core" }
lib-acme = { path = "../../libs/lib-acme" }
# lib-utils = { path = "../../libs/lib-utils" }
# lib-web = { path = "../../libs/lib-web" }
# lib-cli = { path = "../../libs/lib-cli" }
# -- Json
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
strum_macros = { workspace = true }
# -- Others
chrono = { workspace = true }
thiserror = { workspace = true }
# -- Async
tokio = { workspace = true }
# tower = "0.5"
# tower-cookies = { workspace = true }
# tower-http = { workspace = true }
# -- Tracing
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
color-eyre = { workspace = true }

url = { workspace = true }
reqwest = { workspace = true }
clap = { version = "4", features = ["cargo", "derive"] }
inquire = "0.9"
