-- User
create table "user_type" (
  serial_id bigint generated by default as identity (start with 1) primary key,
  typ varchar(32) not null unique,

  -- timestamps
  ctime timestamp with time zone not null default current_timestamp,
  mtime timestamp with time zone not null default current_timestamp
);

insert into "user_type" 
    (serial_id, typ)
values 
    (1, 'Sys'),
    (2, 'User'),
    (3, 'UnVarifiedUser');

create table "users" (
  serial_id bigint generated by default as identity (start with 1000) primary key,

  user_id varchar(30) not null unique,
  email varchar(256) not null unique,
  name varchar(128) not null,
  user_type_serial_id bigint not null default 3, -- 3: UnVarifiedUser

  -- timestamps
  ctime timestamp with time zone not null default current_timestamp,
  mtime timestamp with time zone not null default current_timestamp,
  
  foreign key(user_type_serial_id)
    references user_type (serial_id)
    on update cascade
    on delete restrict
);

create table "password_auth" (
  user_serial_id bigint primary key,

  -- auth
  pwd varchar(256) not null,
  pwd_salt uuid not null,
  token_salt uuid not null default gen_random_uuid(),

  -- timestamps
  ctime timestamp with time zone not null default current_timestamp,
  mtime timestamp with time zone not null default current_timestamp,

  foreign key(user_serial_id) 
    references users (serial_id)
    on update cascade
    on delete restrict
);
