[package]
name = "cert-rs"
version = "0.0.0"
description = "..."
categories = ["acme"]

authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["proxy-manager"]

# [[example]]
# name = "pebble-test"
# path = "examples/pebble-test/src/main.rs"
# test = true

# [[test]]
# name = "pebble"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
# lib-proxy = { path = "../../libs/lib-proxy" }

tokio.workspace = true
url.workspace = true
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
color-eyre.workspace = true

chrono = "0.4"
reqwest = { version = "0.13", features = ["json"] }
http = "1"
mime = "0.3"
openssl = { version = "0.10", features = ["vendored"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = { version = "3" }
tracing = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
], optional = true }

base64 = "0.22"
sha2 = "0.10"

[dev-dependencies]
color-eyre = "0.6"
serial_test = "3"
fake = { version = "4" }

[features]
default = ["tracing"]
tracing = ["dep:tracing", "dep:tracing-subscriber"]
