[package]
name = "cert-rs"
version = "0.0.1"
description = "..."
categories = ["acme"]
authors = ["Zenno Zenith <95485961+ZennoZenith@users.noreply.github.com>"]
license = "MIT OR Apache-2.0"
edition = "2024"
repository = "https://github.com/ZennoZenith/cert-rs"
keywords = ["ssl", "letsencrypt", "acme"]
readme = "README.md"

# [lints.rust]
# unsafe_code = "forbid"
# unused = { level = "allow", priority = -1 } # For exploratory dev.


[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[[example]]
name = "full"
path = "examples/full.rs"
test = true
required-features = ["generate"]


[[example]]
name = "experiment"
path = "examples/experiment.rs"
test = true
required-features = ["generate"]


# [[example]]
# name = "pebble-test"
# path = "examples/pebble-test/src/main.rs"
# test = true

# [[test]]
# name = "pebble"

[dependencies]
chrono = "0.4"
base64 = "0.22"
http = "1"
httpdate = "1.0.3"
mime = "0.3"
reqwest = { version = "0.13", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = "0.28"
strum_macros = "0.28"
# time = { version = "0.3", optional = true }
thiserror = "2"
tokio = { version = "1", features = [
  "macros",
  "rt",
  "rt-multi-thread",
  "time",
] }
tracing = { version = "0.1", optional = true }
url = { version = "2", features = ["serde"] }


## Sha2 latest is 0.11 but rsa uses 0.10
# sha2 = { version = "0.10", default-features = false, features = [
#   # "alloc",
#   # "zeroize",
# ] }
elliptic-curve = { version = "0.13", default-features = false, features = [
  "pkcs8",
] }
pkcs8 = { version = "0.10", default-features = false, features = ["pem"] }
ecdsa = { version = "0.16", default-features = false, features = [
  "alloc",
  "signing",
  "pkcs8",
  "pem",
] }

rsa = { version = "0.9", default-features = false, features = ["pem", "sha2"] }
p256 = { version = "0.13", default-features = false, features = [
  "alloc",
  "ecdsa",
  "pkcs8",
  "pem",
] }
p384 = { version = "0.13", default-features = false, features = [
  "alloc",
  "ecdsa",
  "pkcs8",
  "pem",
] }
p521 = { version = "0.13", default-features = false, features = [
  "alloc",
  "ecdsa",
  "pkcs8",
  "pem",
  "getrandom",
] }

ed25519-dalek = { version = "2", default-features = false, features = [
  "fast",
  "pkcs8",
  "pem",
] }

x509-parser = { version = "0.18", default-features = false }
rcgen = { version = "0.14", default-features = false, features = [
  "pem",
  "crypto",
  "ring",
] }

[dev-dependencies]
clap = { version = "4", features = ["derive"] }
colored = "3"
color-eyre = "0.6"
fake = { version = "4" }
glob = "0.3"
serial_test = "3"
toml = "1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
# default = ["tracing"]
default = ["tracing", "generate"]
tracing = ["dep:tracing"]
generate = ["rcgen/aws_lc_rs"]
verify = ["x509-parser/verify"]

# time = ["dep:time"]
# chrone = ["dep:chrono"]
