name: example_service
services:
  # backend:
  #   build:
  #     context: backend
  #     target: builder
  #   secrets:
  #     - db_password
  #   depends_on:
  #     db:
  #       condition: service_healthy

  database:
    image: postgres:18
    container_name: example_service_example_db
    # user: 1000:1000
    env_file:
      - .env
    environment:
      # POSTGRES_PASSWORD: ${DB_PASSWORD:-welcome} ## required or 
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_DB: ${DB_NAME:-example_db}
    command: postgres
      -c max_connections=1000
      # -c shared_buffers=256MB
    ports:
      - ${DB_PORT:-5432}:5432
    restart: unless-stopped
    secrets:
      - db_password
    volumes:
      - db_data:/var/lib/postgresql
      # - db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      # test: [ "CMD", "pg_isready" ]
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-example_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

secrets:
  db_password:
    file: db/password.txt