[env]
# Scope down tracing, to filter out external lib tracing.
RUST_LOG = "cert_rs=debug,pebble_test=debug"

TEST_ACME_DIR = "https://localhost:24000/dir"
TEST_CHALL_TEST_SRV = "http://localhost:8055"
